// Halloween's markers for a spotlight (named in src/sim/themes.js). See
// src/render/sprites/spotlights.js for what every theme's markers share.
import { PALETTE as P } from '../../sprites/palette.js'
import { INK, drawMarker } from '../../sprites/spotlights.js'

const MARKERS = {
  jack: [[
    '....XXX....',
    '....XsX....',
    '..XXXXXXX..',
    '.XqpppPpqX.',
    'XqpjpPpjppX',
    'XqjjpPpjjpX',
    'XqpppPppppX',
    'XqjpjjjpjpX',
    'XqpjjjjjjpX',
    '.XpppPpppX.',
    '..XXXXXXX..',
    '...........',
  ], { X: INK, p: P.pumpkin, P: P.pumpkinDark, q: P.pumpkinLight, s: P.stalk, j: P.jackGlow }],
  bat: [[
    '...........',
    '...........',
    'X...X.X...X',
    'XX..XbX..XX',
    'XbXXbbbXXbX',
    'XbbbjbjbbbX',
    'XbBbbbbbBbX',
    '.XbXbbbXbX.',
    '..X.XbX.X..',
    '.....X.....',
    '...........',
    '...........',
  ], { X: INK, b: P.batWing, B: P.batWingLight, j: P.jackGlow }],
  ghost: [[
    '...XXXXX...',
    '..XgggggX..',
    '.XgggggggX.',
    '.XgXgggXgX.',
    '.XgXgggXgX.',
    '.XgggXgggX.',
    '.XgggggggX.',
    '.XggggggGX.',
    '.XgggggGGX.',
    '.XgXgXgXGX.',
    '.XX.X.X.XX.',
    '...........',
  ], { X: INK, g: P.boneWhite, G: P.boneShade }],
  'witch-hat': [[
    '.......XX..',
    '......XfX..',
    '.....XffX..',
    '.....XffX..',
    '....XfffX..',
    '....XffffX.',
    '...XfFfffX.',
    '...XtttttX.',
    'XXXXXXXXXXX',
    'XfffFfffffX',
    'XXXXXXXXXXX',
    '...........',
  ], { X: INK, f: P.felt, F: P.feltLight, t: P.feltBand }],
  candle: [[
    '.....X.....',
    '....XcX....',
    '...XcCcX...',
    '...XcCcX...',
    '....XcX....',
    '....XXX....',
    '...XwwWX...',
    '...XwwWX...',
    '...XwwWX...',
    '...XwwWX...',
    '.XXXXXXXXX.',
    '.XWWWWWWWX.',
  ], { X: INK, c: P.candleFlame, C: P.flameCore, w: P.boneWhite, W: P.boneShade }],
}

export const drawHallowSpotlight = (id) => drawMarker(MARKERS, id)
