// The elves' markers for a spotlight (named in src/sim/themes.js): things of the wood that glow or
// shine. See src/render/sprites/spotlights.js for what every theme's markers share.
import { PALETTE as P } from '../../sprites/palette.js'
import { INK, drawMarker } from '../../sprites/spotlights.js'

const MARKERS = {
  leaf: [[
    '.....X.....',
    '....XyX....',
    '...XyyYX...',
    '..XyyyyYX..',
    '..XyyXyYX..',
    '.XyyyXyyYX.',
    '.XyyyXyyYX.',
    '..XyyXyYX..',
    '..XyyXyYX..',
    '...XyXYX...',
    '....XXX....',
    '.....X.....',
  ], { X: INK, y: P.birchGold, Y: P.giltDark }],
  moon: [[
    '....XXXX...',
    '...XnmmX...',
    '..XnmmX....',
    '..XnmX.....',
    '.XnmmX.....',
    '.XnmmX.....',
    '.XnmmX.....',
    '.XnmmmX....',
    '..XnmmmXXX.',
    '..XnmmmmmMX',
    '...XXMMMMX.',
    '.....XXXX..',
  ], { X: INK, m: P.mithril, M: P.mithrilDark, n: P.mithrilLight }],
  lantern: [[
    '.....X.....',
    '....XmX....',
    '...XXXXX...',
    '..XMMMMMX..',
    '..XaaaaaX..',
    '..XawaaaX..',
    '..XawaaaX..',
    '..XaaaaaX..',
    '..XMMMMMX..',
    '...XXXXX...',
    '....XmX....',
    '.....X.....',
  ], { X: INK, m: P.mithril, M: P.mithrilDark, a: P.lanternGlow, w: P.white }],
  crystal: [[
    '.....X.....',
    '....XcX....',
    '...XcwCX...',
    '...XcwCX...',
    '..XccwcCX..',
    '..XccwcCX..',
    '..XcccccX..',
    '..XcccCCX..',
    '...XccCX...',
    '...XccCX...',
    '....XCX....',
    '.....X.....',
  ], { X: INK, c: P.shard, C: P.shardDark, w: P.white }],
  wisp: [[
    '...XXXXX...',
    '..XfffffX..',
    '.XffwwfffX.',
    '.XfwwwwffX.',
    '.XffwwfffX.',
    '.XfffffffX.',
    '..XfffffX..',
    '...XfffX...',
    '....XfX....',
    '....XfX....',
    '.....X.....',
    '...........',
  ], { X: INK, f: P.glowCap, w: P.white }],
}

export const drawElvishSpotlight = (id) => drawMarker(MARKERS, id)
