// The site's markers for a spotlight (named in src/sim/themes.js): things a site already uses to
// say "look here". See src/render/sprites/spotlights.js for what every theme's markers share.
import { PALETTE as P } from '../../sprites/palette.js'
import { INK, drawMarker } from '../../sprites/spotlights.js'

const MARKERS = {
  cone: [[
    '.....X.....',
    '....XoX....',
    '....XoX....',
    '...XoooX...',
    '...XwwwX...',
    '..XoooooX..',
    '..XwwwwwX..',
    '.XoooooOOX.',
    '.XoooooOOX.',
    'XXXXXXXXXXX',
    'XkkkkkkkkkX',
    'XXXXXXXXXXX',
  ], { X: INK, o: P.safetyOrange, O: P.safetyOrangeDark, w: P.reflective, k: P.asphaltDark }],
  'hard-hat': [[
    '...........',
    '...........',
    '...XXXXX...',
    '..XhhXhhX..',
    '.XhwhXhhhX.',
    '.XhwhXhhhX.',
    '.XhhhXhhdX.',
    'XXXXXXXXXXX',
    'XhhhhhhhhdX',
    'XXXXXXXXXXX',
    '...........',
    '...........',
  ], { X: INK, h: P.hardHat[0], d: P.sitePaint[1], w: P.white }],
  hook: [[
    '....XXX....',
    '....XsX....',
    '..XXXXXXX..',
    '..XyyyyyX..',
    '..XkykykX..',
    '..XXXXXXX..',
    '....XsX....',
    '.....XsX...',
    '.X....XsX..',
    'XsX...XsX..',
    '.XsXXXsX...',
    '..XXXXX....',
  ], { X: INK, s: P.steel, y: P.hiVis[0], k: P.asphaltDark }],
  warning: [[
    '.....X.....',
    '....XvX....',
    '....XvX....',
    '...XvvvX...',
    '...XvXvX...',
    '..XvvXvvX..',
    '..XvvXvvX..',
    '.XvvvvvvvX.',
    '.XvvvXvvvX.',
    'XvvvvvvvvvX',
    'XXXXXXXXXXX',
    '...........',
  ], { X: INK, v: P.hardHat[0] }],
  beacon: [[
    '...........',
    '....XXX....',
    '...XoooX...',
    '..XowooOX..',
    '..XowooOX..',
    '..XooooOX..',
    '..XooooOX..',
    '.XXXXXXXXX.',
    '.XkkkkkkkX.',
    '.XXXXXXXXX.',
    '...........',
    '...........',
  ], { X: INK, o: P.flameTip, O: P.safetyOrange, w: P.flameCore, k: P.asphaltDark }],
}

export const drawSiteSpotlight = (id) => drawMarker(MARKERS, id)
