// Thanksgiving's markers for a spotlight (named in src/sim/themes.js). See
// src/render/sprites/spotlights.js for what every theme's markers share.
import { PALETTE as P } from '../../sprites/palette.js'
import { INK, drawMarker } from '../../sprites/spotlights.js'

const MARKERS = {
  maple: [[
    '.....X.....',
    '....XrX....',
    '.X.XrrrX.X.',
    'XrXXrrrXXrX',
    'XrrrrrrrrrX',
    '.XrrrRrrrX.',
    'XrrrrRrrrrX',
    '.XXrrRrrXX.',
    '...XXRXX...',
    '....XRX....',
    '....XoX....',
    '.....X.....',
  ], { X: INK, r: P.mapleRed, R: P.mapleRedDark, o: P.oakBrown }],
  acorn: [[
    '.....X.....',
    '....XoX....',
    '..XXXXXXX..',
    '.XoOoOoOoX.',
    '.XOoOoOoOX.',
    '..XXXXXXX..',
    '..XaaaaaX..',
    '..XwaaaAX..',
    '..XaaaaAX..',
    '...XaaAX...',
    '....XAX....',
    '.....X.....',
  ], { X: INK, o: P.oakBrown, O: P.barnwoodDark, a: P.acorn, A: P.crustDark, w: P.crustLight }],
  pie: [[
    '...........',
    '...........',
    '...XXXXX...',
    '.XXcCcCcXX.',
    'XcccccccccX',
    'XcCcCcCcCcX',
    'XfffffffffX',
    'XCcCcCcCcCX',
    '.XCCCCCCCX.',
    '..XXXXXXX..',
    '...........',
    '...........',
  ], { X: INK, c: P.crust, C: P.crustDark, f: P.pieFilling }],
  corn: [[
    '....XXX....',
    '...XkKkX...',
    '...XKkPX...',
    '...XkPkX...',
    '.X.XPkKX.X.',
    'XhXXkKkXXhX',
    'XhhXKkPXhhX',
    '.XhhXkXhhX.',
    '..XhhXhhX..',
    '...XHhHX...',
    '....XHX....',
    '.....X.....',
  ], { X: INK, k: P.kernelGold, K: P.kernelRed, P: P.kernelPlum, h: P.husk, H: P.huskDark }],
  turkey: [[
    '..XXXXXXX..',
    '.XgrgrgrgX.',
    'XgrgXXXgrgX',
    'XrgXhXhXgrX',
    'XgrXhyhXrgX',
    'XrgXXwXXgrX',
    'XgXoooooXgX',
    '.XoooooooX.',
    '.XoOoooOoX.',
    '..XoooooX..',
    '...XyXyX...',
    '...........',
  ], { X: INK, g: P.birchGold, r: P.mapleRed, h: P.crustLight, y: P.gilt, w: P.cranberry, o: P.oakBrown, O: P.barnwoodDark }],
}

export const drawHarvestSpotlight = (id) => drawMarker(MARKERS, id)
