// The farm's markers for a spotlight (named in src/sim/themes.js). See
// src/render/sprites/spotlights.js for what every theme's markers share.
import { PALETTE as P } from '../../sprites/palette.js'
import { INK, drawMarker } from '../../sprites/spotlights.js'

const MARKERS = {
  apple: [[
    '.....X.XX..',
    '....XtXllX.',
    '..XXXtXXX..',
    '.XaaaXaaaX.',
    'XawaaaaaaRX',
    'XawaaaaaaRX',
    'XaaaaaaaaRX',
    'XaaaaaaaaRX',
    '.XaaaaaaRX.',
    '.XaaaaaRRX.',
    '..XXXXXXX..',
    '...........',
  ], { X: INK, a: P.apple, R: P.mapleRedDark, w: P.white, t: P.oakBrown, l: P.vegLeaf }],
  hen: [[
    '..XcX......',
    '.XcccX.....',
    '.XhXhX.....',
    'XbhhhhX....',
    '.XhhhhX.XX.',
    '.XhhhhhXhX.',
    '.XhhhhhhhX.',
    '.XhhBhhhhX.',
    '..XhBBhhX..',
    '...XhhhX...',
    '...XbXbX...',
    '...........',
  ], { X: INK, h: P.hen, c: P.henComb, b: P.henBeak, B: P.henBrown }],
  bale: [[
    '...........',
    '...........',
    '.XXXXXXXXX.',
    'XlhhhhhhhdX',
    'XlhdhhdhhdX',
    'XlhhhhhhhdX',
    'XtttttttttX',
    'XlhhdhhdhdX',
    'XlhhhhhhhdX',
    'XdddddddddX',
    'XXXXXXXXXXX',
    '...........',
  ], { X: INK, h: P.hay, d: P.hayDark, l: P.hayLight, t: P.oakBrown }],
  sunflower: [[
    '...XX.XX...',
    '..XyyXyyX..',
    '.XyyXXXyyX.',
    'XyyXcccXyyX',
    '.XXcCcCcXX.',
    'XyyXcccXyyX',
    '.XyyXXXyyX.',
    '..XyyXyyX..',
    '...XXlXX...',
    '....XlX....',
    '...XlXlX...',
    '....XlX....',
  ], { X: INK, y: P.kernelGold, c: P.barnwoodDark, C: P.oakBrown, l: P.vegLeaf }],
  churn: [[
    '...XXXXX...',
    '...XMMMX...',
    '....XmX....',
    '...XmmmX...',
    '..XnmmmMX..',
    '..XnmmmMX..',
    '..XXXXXXX..',
    '..XnmmmMX..',
    '..XnmmmMX..',
    '..XnmmmMX..',
    '..XXXXXXX..',
    '...........',
  ], { X: INK, m: P.tin, M: P.tinDark, n: P.tinLight }],
}

export const drawFarmSpotlight = (id) => drawMarker(MARKERS, id)
