// New Year's Eve's markers for a spotlight (named in src/sim/themes.js). See
// src/render/sprites/spotlights.js for what every theme's markers share.
import { PALETTE as P } from '../../sprites/palette.js'
import { INK, drawMarker } from '../../sprites/spotlights.js'

const MARKERS = {
  firework: [[
    '.....X.....',
    '....XmX....',
    '...XmmmX...',
    '...XwwwX...',
    '...XwbwX...',
    '...XwwwX...',
    '.XXXmmmXXX.',
    'XmmXXXXXmmX',
    'XXX.XyX.XXX',
    '....XoX....',
    '...XyoyX...',
    '....XXX....',
  ], { X: INK, m: P.nyePaint[0], w: P.nyePaint[4], b: P.nyePaint[2], y: P.nyeSpark[1], o: P.nyeSpark[2] }],
  'party-hat': [[
    '....XwX....',
    '...XwwwX...',
    '....XmX....',
    '....XmX....',
    '...XmwmX...',
    '...XmmmX...',
    '..XmwmwmX..',
    '..XmmmmmX..',
    '.XmwmmmwmX.',
    '.XmmmmmmmX.',
    'XgggggggggX',
    'XXXXXXXXXXX',
  ], { X: INK, m: P.nyePaint[0], w: P.nyeSpark[0], g: P.nyePaint[1] }],
  champagne: [[
    '..XXXXXXX..',
    '..XyyyyyX..',
    '..XyGyyyX..',
    '..XyyGyyX..',
    '...XyyyX...',
    '...XyGyX...',
    '....XyX....',
    '....XwX....',
    '....XwX....',
    '....XwX....',
    '..XXXwXXX..',
    '..XwwwwwX..',
  ], { X: INK, y: P.nyePaint[1], G: P.nyeSpark[0], w: P.nyeMarble }],
  clock: [[
    '...XXXXX...',
    '..XgggggX..',
    '.XgcccccgX.',
    'XgcccMcccgX',
    'XgccHMcccgX',
    'XgTcHMccTgX',
    'XgcccKcccgX',
    'XgcccTcccgX',
    '.XgcccccgX.',
    '..XgggggX..',
    '...XXXXX...',
    '....XXX....',
  ], { X: INK, g: P.gilt, c: P.nyeClockFace, M: P.nyePaint[0], H: P.nyeWandDark, K: P.giltDark, T: P.nyeWandDark }],
  disco: [[
    '.....X.....',
    '..y..X..y..',
    '...XXXXX...',
    '..XsSsSsX..',
    '.XSsTsSsSX.',
    '.XsSsSsTsX.',
    '.XSsSTsSsX.',
    '.XsSsSsSsX.',
    '..XSsSsSX..',
    '...XXXXX...',
    '.y...y...y.',
    '...........',
  ], { X: INK, s: P.nyePaint[7], S: P.nyeWand, T: P.nyeSpark[0], y: P.nyeSpark[1] }],
}

export const drawPartySpotlight = (id) => drawMarker(MARKERS, id)
